services:
  learning_base:
    build: .
    image:  rakeshadepu/learningbase_economic_forecast_across_german_states
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/;
volumes:
  ai_system:
    external: true